---
- hosts: general
  remote_user: ubuntu
  tasks:
    - include_vars: vars.yml
    - name: set readable host name
      become: true
      hostname: name="{{inventory_hostname}}"

    - name: add ppas
      become: true
      apt_repository: repo="{{item}}" state=present
      with_items: "{{ppas}}"

    - name: node ppa
      become: true
      shell: curl -sL https://deb.nodesource.com/setup_{{node_version}}.x | sudo -E bash -

    - name: install node
      become: true
      apt: pkg={{item}} force=true update_cache=yes
      with_items:
        - nodejs
        - nodejs-dbg

    - name: npm install some things
      become: true
      command: "npm install -g npm@latest json@latest json-diff@latest yarn"

    - name: install all apt packages
      become: true
      apt: pkg={{item}} state=present force=true update_cache=yes
      with_items: "{{packages}}"

    # remove comment out if you use sslcert
    #- name: create cert dir
    #  become: true
    #  file:
    #    path: "{{install_dir}}/certs"
    #    state: directory
    #    mode: 0600
    #- name: copy TLS certs
    #  become: true
    #  copy:
    #    src: "../certs/{{item}}"
    #    dest: "/{{install_dir}}/certs/{{item}}"
    #    mode: 0600
    #  with_items:
    #    - "{{hostname}}.pem"
    #    - "{{hostname}}.key"

    - name: install bundler
      become: true
      command: gem install bundler

    - name: ensure database is created
      become: true
      become_user: postgres
      postgresql_db: name={{dbname}}

    - name: ensure user has access to database
      become: true
      become_user: postgres
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

    - name: ensure user dos not have unneccessry privilege
      become: true
      become_user: postgres
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

    - name: ensure no other user can access the database
      become: true
      become_user: postgres
      postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
