---
- hosts: general
  remote_user: ubuntu
  tasks:
    - include_vars: "{{ item }}"
      with_items:
        - vars.yml
        - encrypted_vars.yml

    - name: copy production variables
      template:
        src: templates/env.production
        dest: "{{install_dir}}/live/.env.production"

    - name: remove default config
      become: yes
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: copy nginx config
      become: true
      template:
        src: templates/nginx.conf
        dest: "/etc/nginx/sites-enabled/{{web_hostname}}"

    - name: restart nginx
      become: true
      service: name=nginx state=restarted

    - name: create systemd config for mastodon
      become: true
      template:
        src: "templates/mastodon-{{item}}.service"
        dest: "/etc/systemd/system/mastodon-{{item}}.service"
      with_items: "{{services}}"

    - name: create systemd config for prometheus
      become: true
      template:
        src: "templates/prometheus-{{item}}.service"
        dest: "/etc/systemd/system/prometheus-{{item}}.service"
      with_items: "{{prometheus_services}}"

    - name: start and enable systemd services
      become: true
      with_items: "{{services}}"
      systemd:
        name: "mastodon-{{item}}"
        state: started
        enabled: yes
        daemon_reload: yes

    - name: reload systemd services
      become: true
      with_items: "{{services}}"
      systemd:
        name: "mastodon-{{item}}"
        state: restarted
        daemon_reload: yes

    - name: start and enable systemd services for prometheus
      become: true
      with_items: "{{prometheus_services}}"
      systemd:
        name: "prometheus-{{item}}"
        state: started
        enabled: yes
        daemon_reload: yes

    - name: reload systemd services for prometheus
      become: true
      with_items: "{{prometheus_services}}"
      systemd:
        name: "prometheus-{{item}}"
        state: restarted
        daemon_reload: yes
